# Generated by Django 3.1.7 on 2021-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(choices=[('ARMANI', 'ARMANI'), ('H&M', 'H&M'), ('LEVIS', 'LEVIS'), ('LOUIS VUITTON', 'LOUIS VUITTON'), ('GUCCI', 'GUCCI'), ('TOMMY HILFIGER', 'TOMMY HILFIGER'), ('NIKE', 'NIKE'), ('ZARA', 'ZARA'), ('ADDIDAS', 'ADDIDAS')], max_length=100),
        ),
    ]
